@file:Suppress("MagicNumber") // Genres list below is actual id from web, not magic number
package io.github.gawgua.tachiyomi.extension.vi.mimihentai.models.dto

import kotlinx.serialization.Serializable

@Serializable
data class Genre(
    val id: Int,
    val name: String,
    val description: String?,
    val mangaCount: Int?,
)

val GENRES by lazy {
    listOf(
        Genre(416, "3D", null, null),
        Genre(417, "Action", null, null),
        Genre(406, "Adult", null, null),
        Genre(457, "Adventure", null, null),
        Genre(267, "Ahegao", null, null),
        Genre(343, "Alien", null, null),
        Genre(183, "Anal", null, null),
        Genre(452, "Angel", null, null),
        Genre(239, "Aphrodisiac", null, null),
        Genre(502, "Apron", null, null),
        Genre(212, "Armpit", null, null),
        Genre(221, "Artist CG", null, null),
        Genre(556, "ArtistCG có thoại", null, null),
        Genre(338, "Assjob", null, null),
        Genre(259, "Aunt", null, null),
        Genre(389, "BBM", null, null),
        Genre(311, "BBW", null, null),
        Genre(182, "BDSM", null, null),
        Genre(303, "Bald", null, null),
        Genre(377, "Band-Aid", null, null),
        Genre(352, "Bestiality", null, null),
        Genre(261, "Big boobs", null, null),
        Genre(337, "Bike shorts", null, null),
        Genre(277, "Bikini", null, null),
        Genre(315, "Bisexual", null, null),
        Genre(265, "Black mail", null, null),
        Genre(187, "Black skin", null, null),
        Genre(173, "Blindfold", null, null),
        Genre(231, "Bloomer", null, null),
        Genre(314, "Blowjob", null, null),
        Genre(288, "Body Writing", null, null),
        Genre(339, "Bodysuit", null, null),
        Genre(208, "Bodyswap", null, null),
        Genre(179, "Bondage", null, null),
        Genre(414, "Breast Sucking", null, null),
        Genre(345, "Breast feeding", null, null),
        Genre(275, "Brother", null, null),
        Genre(178, "Bukkake", null, null),
        Genre(195, "Bunny Girl", null, null),
        Genre(210, "Catgirl", null, null),
        Genre(340, "Chastity belt", null, null),
        Genre(186, "Cheating", null, null),
        Genre(168, "Cheerleader", null, null),
        Genre(176, "Chikan", null, null),
        Genre(193, "Chubby", null, null),
        Genre(335, "Clone", null, null),
        Genre(324, "Clothed M nude F", null, null),
        Genre(313, "Collar", null, null),
        Genre(245, "Color", null, null),
        Genre(411, "Comedy", null, null),
        Genre(553, "Comic", null, null),
        Genre(302, "Condom", null, null),
        Genre(177, "Cosplay", null, null),
        Genre(357, "Cousin", null, null),
        Genre(325, "Crossdressing", null, null),
        Genre(317, "Crotch tattoo", null, null),
        Genre(334, "Cum swap", null, null),
        Genre(220, "Cunnilingus", null, null),
        Genre(233, "Có che", null, null),
        Genre(167, "DILF", null, null),
        Genre(270, "Daughter", null, null),
        Genre(174, "Deepthroat", null, null),
        Genre(175, "Demon", null, null),
        Genre(349, "Dickgirl on dickgirl", null, null),
        Genre(308, "Dickgirl on female", null, null),
        Genre(381, "Dickgirl on male", null, null),
        Genre(418, "Dirty", null, null),
        Genre(226, "Dirty Old Man", null, null),
        Genre(207, "Doggirl", null, null),
        Genre(229, "Double Penetration", null, null),
        Genre(304, "Double blowjob", null, null),
        Genre(244, "Doujinshi", null, null),
        Genre(219, "Drama", null, null),
        Genre(293, "Drug", null, null),
        Genre(344, "Drunk", null, null),
        Genre(234, "Ecchi", null, null),
        Genre(181, "Elf", null, null),
        Genre(323, "Emotionless", null, null),
        Genre(188, "Exhibitionist", null, null),
        Genre(382, "Eye-covering bang", null, null),
        Genre(305, "Eyepatch", null, null),
        Genre(320, "FFF Threesome", null, null),
        Genre(329, "FFM Threesome", null, null),
        Genre(363, "FFT Threesome", null, null),
        Genre(225, "Face Mask", null, null),
        Genre(307, "Facesitting", null, null),
        Genre(264, "Family", null, null),
        Genre(222, "Fang", null, null),
        Genre(408, "Fantasy", null, null),
        Genre(316, "Father", null, null),
        Genre(355, "Females only", null, null),
        Genre(156, "Femdom", null, null),
        Genre(326, "Feminization", null, null),
        Genre(289, "Filming", null, null),
        Genre(169, "Fingering", null, null),
        Genre(159, "Fisting", null, null),
        Genre(332, "Foot licking", null, null),
        Genre(189, "Footjob", null, null),
        Genre(217, "Foxgirl", null, null),
        Genre(552, "Furry", null, null),
        Genre(184, "Futanari", null, null),
        Genre(368, "Gag", null, null),
        Genre(155, "Gangbang", null, null),
        Genre(372, "Gaping", null, null),
        Genre(356, "Garter belt", null, null),
        Genre(284, "GenderBender", null, null),
        Genre(246, "Ghost", null, null),
        Genre(185, "Glasses", null, null),
        Genre(361, "Glory hole", null, null),
        Genre(254, "Godness", null, null),
        Genre(330, "Gothic lolita", null, null),
        Genre(410, "Group", null, null),
        Genre(397, "Guro", null, null),
        Genre(160, "Gyaru", null, null),
        Genre(353, "Gymshorts", null, null),
        Genre(394, "Hairjob", null, null),
        Genre(236, "Hairy", null, null),
        Genre(306, "Handicapped", null, null),
        Genre(203, "Handjob", null, null),
        Genre(191, "Harem", null, null),
        Genre(251, "Heart Pupils", null, null),
        Genre(403, "HentaiVN", null, null),
        Genre(386, "Hidden sex", null, null),
        Genre(453, "Historical", null, null),
        Genre(224, "Horns", null, null),
        Genre(253, "Horror", null, null),
        Genre(232, "Housewife", null, null),
        Genre(157, "Huge Ass", null, null),
        Genre(190, "Huge Boobs", null, null),
        Genre(281, "Huge Dick", null, null),
        Genre(347, "Humiliation", null, null),
        Genre(237, "Idol", null, null),
        Genre(283, "Imouto", null, null),
        Genre(321, "Impregnation", null, null),
        Genre(158, "Incest", null, null),
        Genre(367, "Invisible", null, null),
        Genre(230, "Isekai", null, null),
        Genre(214, "Kemonomimi", null, null),
        Genre(235, "Kimono", null, null),
        Genre(390, "Kissing", null, null),
        Genre(228, "Kuudere", null, null),
        Genre(604, "Lactation", null, null),
        Genre(318, "Leash", null, null),
        Genre(309, "Leg lock", null, null),
        Genre(238, "Lingerie", null, null),
        Genre(154, "Loli", null, null),
        Genre(280, "MILF", null, null),
        Genre(395, "MMF Threesome", null, null),
        Genre(333, "MMT Threesome", null, null),
        Genre(376, "MTF Threesome", null, null),
        Genre(247, "Magical Girl", null, null),
        Genre(197, "Maid", null, null),
        Genre(351, "Male on dickgirl", null, null),
        Genre(384, "Males only", null, null),
        Genre(503, "Manhua", null, null),
        Genre(266, "Manhwa", null, null),
        Genre(278, "Masturbation", null, null),
        Genre(419, "Mature", null, null),
        Genre(331, "Mermaid", null, null),
        Genre(412, "Miko", null, null),
        Genre(170, "Milking", null, null),
        Genre(292, "Mind Control", null, null),
        Genre(291, "Mind break", null, null),
        Genre(420, "Monster", null, null),
        Genre(243, "Monster Girl", null, null),
        Genre(162, "Mother", null, null),
        Genre(360, "Muscle", null, null),
        Genre(161, "NTR", null, null),
        Genre(216, "Nakadashi", null, null),
        Genre(269, "Neighbor", null, null),
        Genre(257, "Netori", null, null),
        Genre(287, "Ninja", null, null),
        Genre(310, "Nipple fuck", null, null),
        Genre(375, "Nipple stimulation", null, null),
        Genre(387, "No penetration", null, null),
        Genre(554, "Non-hen", null, null),
        Genre(271, "Nun", null, null),
        Genre(242, "Nurse", null, null),
        Genre(255, "Office lady", null, null),
        Genre(407, "Old Man", null, null),
        Genre(273, "Oneshot", null, null),
        Genre(346, "Oppai loli", null, null),
        Genre(198, "Oral", null, null),
        Genre(202, "Orc", null, null),
        Genre(258, "Osananajimi", null, null),
        Genre(250, "Paizuri", null, null),
        Genre(279, "Pantyhose", null, null),
        Genre(312, "Pegging", null, null),
        Genre(399, "Piercing", null, null),
        Genre(398, "Piss drinking", null, null),
        Genre(319, "Pole dancing", null, null),
        Genre(369, "Ponytails", null, null),
        Genre(276, "Pregnant", null, null),
        Genre(322, "Priest", null, null),
        Genre(218, "Princess", null, null),
        Genre(163, "Prostitution", null, null),
        Genre(204, "Public", null, null),
        Genre(294, "Rape", null, null),
        Genre(336, "Rimjob", null, null),
        Genre(402, "Romance", null, null),
        Genre(422, "Ryona", null, null),
        Genre(374, "Saliva", null, null),
        Genre(380, "Scar", null, null),
        Genre(350, "Scat", null, null),
        Genre(404, "School Uniform", null, null),
        Genre(241, "Schoolgirl", null, null),
        Genre(172, "Sci-fi", null, null),
        Genre(153, "Series", null, null),
        Genre(152, "Sex toys", null, null),
        Genre(201, "Short hair", null, null),
        Genre(165, "Shota", null, null),
        Genre(199, "Sister", null, null),
        Genre(290, "Sixty-Nine", null, null),
        Genre(282, "Slave", null, null),
        Genre(268, "Sleeping", null, null),
        Genre(211, "Slut", null, null),
        Genre(180, "Small Chest", null, null),
        Genre(192, "Socks", null, null),
        Genre(328, "Solo action", null, null),
        Genre(458, "Son", null, null),
        Genre(327, "Spanking", null, null),
        Genre(415, "Sports", null, null),
        Genre(200, "Squirting", null, null),
        Genre(194, "Stocking", null, null),
        Genre(354, "Stomach deformation", null, null),
        Genre(359, "Strap-on", null, null),
        Genre(240, "Succubus", null, null),
        Genre(164, "Sukumizu", null, null),
        Genre(455, "Supernatural", null, null),
        Genre(362, "Sweating", null, null),
        Genre(205, "Swimsuit", null, null),
        Genre(385, "TTF Threesome", null, null),
        Genre(370, "TTM Threesome", null, null),
        Genre(383, "TTT Threesome", null, null),
        Genre(348, "Table masturbation", null, null),
        Genre(391, "Tail plug", null, null),
        Genre(454, "Tall Girl", null, null),
        Genre(285, "Tan", null, null),
        Genre(206, "Tattoo", null, null),
        Genre(209, "Teacher", null, null),
        Genre(227, "Tentacles", null, null),
        Genre(171, "Thigh Job", null, null),
        Genre(262, "Time stop", null, null),
        Genre(215, "Tomboy", null, null),
        Genre(405, "Tracksuit", null, null),
        Genre(409, "Transformation", null, null),
        Genre(341, "Transparent clothing", null, null),
        Genre(213, "Trap", null, null),
        Genre(392, "Triple penetraion", null, null),
        Genre(256, "Tsundere", null, null),
        Genre(388, "Twins", null, null),
        Genre(371, "Twintails", null, null),
        Genre(260, "Ugly Bastard", null, null),
        Genre(223, "Uncensored", null, null),
        Genre(342, "Underwater", null, null),
        Genre(379, "Urination", null, null),
        Genre(396, "Vaginal sticker", null, null),
        Genre(421, "Vampire", null, null),
        Genre(166, "Vanilla", null, null),
        Genre(249, "Virgin", null, null),
        Genre(393, "Voyeurism", null, null),
        Genre(358, "Vtuber", null, null),
        Genre(263, "Webtoon", null, null),
        Genre(365, "Wet clothes", null, null),
        Genre(272, "Widow", null, null),
        Genre(378, "Wormhole", null, null),
        Genre(366, "Wrestling", null, null),
        Genre(252, "X-ray", null, null),
        Genre(248, "Yandere", null, null),
        Genre(196, "Yaoi", null, null),
        Genre(286, "Younger brother", null, null),
        Genre(274, "Yuri", null, null),
        Genre(373, "Zombie", null, null),
        Genre(364, "exposed clothing", null, null),
        Genre(413, "Áo dài", null, null),
        Genre(456, "Ảnh động", null, null),
    )
}
